name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  
  - type: input
    id: package
    attributes:
      label: Package
      description: Which package is affected?
      placeholder: "@x402/proxy"
    validations:
      required: true
  
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Start proxy with config...
        2. Send request...
        3. See error...
    validations:
      required: true
  
  - type: input
    id: version
    attributes:
      label: Version
      description: What version are you using?
      placeholder: "0.1.0"
    validations:
      required: true
  
  - type: dropdown
    id: runtime
    attributes:
      label: Runtime
      options:
        - Node.js
        - Cloudflare Workers
        - Vercel Edge
        - Other
    validations:
      required: true
